name: Bot Discord

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci --include=dev

  migrate:
    runs-on: ubuntu-latest
    needs: check
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          envkey_DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
          envkey_WEB_PORT: ${{ secrets.WEB_PORT }}
          envkey_WEB_SECRET: ${{ secrets.WEB_SECRET }}
          envkey_XP_PER_MESSAGE: ${{ secrets.XP_PER_MESSAGE }}
          envkey_XP_COOLDOWN: ${{ secrets.XP_COOLDOWN }}
          envkey_LEVEL_MULTIPLIER: ${{ secrets.LEVEL_MULTIPLIER }}

  deploy:
    runs-on: ubuntu-latest
    needs: migrate
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
